all:
	gcc server.c -o server -lpthread
	gcc client.c -o client
	gcc echoService.c -o echoService
	gcc smallToCapital.c -o smallToCapital
	gcc capitalToSmall.c -o capitalToSmall
	gcc timeService.c -o timeService
clean:
	rm -f server client smallToCapital capitalToSmall timeService